name: orrento
description: A new Flutter project.

publish_to: 'none' # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  google_fonts: ^4.0.4
  http: ^0.13.6
  flutter_google_places_hoc081098: ^1.0.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  google_maps_flutter: ^2.5.0
  google_maps_webservice: ^0.0.20-nullsafety
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  permission_handler: ^11.3.0
  location: ^5.0.3
  smooth_page_indicator: ^1.2.0
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# ✅ FIX for google_api_headers crash
dependency_overrides:
  google_api_headers:
    git:
      url: https://github.com/zeshuaro/google_api_headers.git
      ref: main

flutter:
  uses-material-design: true

  assets:
    - assets/images/landing_illustration.png
    - assets/images/googleicon.png
    - assets/images/
    - assets/images/categories/
